#include "images.h"

const ext_img_desc_t images[35] = {
    { "icon_location_11p", &img_icon_location_11p },
    { "icon_temp_22p", &img_icon_temp_22p },
    { "icon_max_11p", &img_icon_max_11p },
    { "icon_min_11p", &img_icon_min_11p },
    { "icon_humd_22p", &img_icon_humd_22p },
    { "icon_wind_11p", &img_icon_wind_11p },
    { "icon_pressure_11p", &img_icon_pressure_11p },
    { "icon_visibility_11p", &img_icon_visibility_11p },
    { "icon_01d_72p", &img_icon_01d_72p },
    { "icon_01n_72p", &img_icon_01n_72p },
    { "icon_02d_72p", &img_icon_02d_72p },
    { "icon_02n_72p", &img_icon_02n_72p },
    { "icon_03d_03n_72p", &img_icon_03d_03n_72p },
    { "icon_04d_04n_72p", &img_icon_04d_04n_72p },
    { "icon_09d_09n_72p", &img_icon_09d_09n_72p },
    { "icon_10d_72p", &img_icon_10d_72p },
    { "icon_10n_72p", &img_icon_10n_72p },
    { "icon_11d_11n_72p", &img_icon_11d_11n_72p },
    { "icon_13d_13n_72p", &img_icon_13d_13n_72p },
    { "icon_50d_50n_72p", &img_icon_50d_50n_72p },
    { "setting1", &img_setting1 },
    { "setting2", &img_setting2 },
    { "logo_lvgl", &img_logo_lvgl },
    { "logo_procs", &img_logo_procs },
    { "logo_temp_cpu", &img_logo_temp_cpu },
    { "logo_use_cpu", &img_logo_use_cpu },
    { "logo_rpm_fan", &img_logo_rpm_fan },
    { "logo_free_ram", &img_logo_free_ram },
    { "logo_use_ram", &img_logo_use_ram },
    { "logo_free_hdd", &img_logo_free_hdd },
    { "logo_use_hdd", &img_logo_use_hdd },
    { "logo_temp_gpu", &img_logo_temp_gpu },
    { "logo_bitcoin", &img_logo_bitcoin },
    { "logo_ethereum", &img_logo_ethereum },
    { "logo_temp_hdd", &img_logo_temp_hdd },
};
